
export const FILTER_BY_STATUS = "FILTER_BY_STATUS";
export const REMOVE_FILTER = "REMOVE_FILTER";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOGOUT = "LOGOUT";
export const GET_TASKS = "GET_TASKS"
export const ADD_TASK = "ADD_TASK";
export const UPDATE_TASK = "UPDATE_TASK";
export const DELETE_TASK = "DELETE_TASK";
export const ADD_TECHNICIAN = "ADD_TECHNICIAN"
export const UPDATE_TECHNICIAN = "UPDATE_TECHNICIAN"
export const DELETE_TECHNICIAN = "DELETE_TECHNICIAN"
export const GET_TECHNICIANS = "GET_TECHNICIANS"
export const ADD_APARTMENT = "ADD_APARTMENT"
export const UPDATE_APARTMENT = "UPDATE_APARTMENT"
export const DELETE_APARTMENT = "DELETE_APARTMENT"
export const GET_APARTMENTS = "GET_APARTMENTS"